package com.projectj.api.common.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode{
	INVALID_REQUEST(HttpStatus.BAD_REQUEST, "INVALID_REQUEST"),
	VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "VALIDATION_ERROR"),
	PLAYER_NOT_FOUND(HttpStatus.NOT_FOUND, "PLAYER_NOT_FOUND"),
	GAME_SETTINGS_NOT_FOUND(HttpStatus.INTERNAL_SERVER_ERROR, "GAME_SETTINGS_NOT_FOUND"),
	REGION_NOT_FOUND(HttpStatus.NOT_FOUND, "REGION_NOT_FOUND"),
	RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "RESOURCE_NOT_FOUND"),
	RECIPE_NOT_FOUND(HttpStatus.NOT_FOUND, "RECIPE_NOT_FOUND"),
	TOOL_NOT_FOUND(HttpStatus.NOT_FOUND, "TOOL_NOT_FOUND"),
	PORTAL_RULE_NOT_FOUND(HttpStatus.NOT_FOUND, "PORTAL_RULE_NOT_FOUND"),
	UPGRADE_NOT_FOUND(HttpStatus.NOT_FOUND, "UPGRADE_NOT_FOUND"),
	INVALID_PHASE(HttpStatus.CONFLICT, "INVALID_PHASE"),
	INVALID_REGION(HttpStatus.CONFLICT, "INVALID_REGION"),
	PORTAL_NOT_ACCESSIBLE(HttpStatus.CONFLICT, "PORTAL_NOT_ACCESSIBLE"),
	TOOL_REQUIRED(HttpStatus.CONFLICT, "TOOL_REQUIRED"),
	REPUTATION_REQUIRED(HttpStatus.CONFLICT, "REPUTATION_REQUIRED"),
	INVENTORY_CAPACITY_EXCEEDED(HttpStatus.CONFLICT, "INVENTORY_CAPACITY_EXCEEDED"),
	INSUFFICIENT_RESOURCE(HttpStatus.CONFLICT, "INSUFFICIENT_RESOURCE"),
	STORAGE_ONLY_IN_HUB(HttpStatus.CONFLICT, "STORAGE_ONLY_IN_HUB"),
	RECIPE_NOT_SELECTED(HttpStatus.CONFLICT, "RECIPE_NOT_SELECTED"),
	UPGRADE_NOT_AVAILABLE(HttpStatus.CONFLICT, "UPGRADE_NOT_AVAILABLE"),
	UPGRADE_ALREADY_PURCHASED(HttpStatus.CONFLICT, "UPGRADE_ALREADY_PURCHASED");

	private final HttpStatus httpStatus;
	private final String code;

	ErrorCode(HttpStatus httpStatus, String code){
		this.httpStatus = httpStatus;
		this.code = code;
	}

	public HttpStatus getHttpStatus(){
		return httpStatus;
	}

	public String getCode(){
		return code;
	}

}
